<!-- page aceuil -->
<h1>la Passion Street Art dans la région de Lyon</h1>

<section class="article">
	<!-- salutation -->
	
    <p class="center">
	<strong>
         <?php if (isset($_SESSION['auth'])) : ?>
        <?= bienvenu(); ?> <?= $_SESSION['auth']['pseudo'] ?>
        <?php else : ?>
        <?= bienvenu(); ?>
		<?php endif ?>
    </strong>
    </p>
   	<p>
		Vous allez découvrir ou redécouvrir l'Art urbain de votre ville.
	</p>
	<p>
		Voir des oeuvres encore visible et revoir des anciennes qui ont étais éffacée.
	</p>
	<p>
		Pensez a nous faire vos proposition de street art sur la page
		<a href='<?= $this->index ?>suggestion' title="suggestion">Suggestion</a>.
	</p>
	<p>
		Déja <?= $count['total'] ?> street Art inscrite dans notre base,
	</p>
	<p>
	a cet art éphémère <?= $count['totalEffacee'] ?> sont éffacée de leur mur, mais pas sur le notre.
	</p>
	<p>
    	Trois exemples de street Art de notre
		<a href='<?= $this->index ?>galerie' title="galerie">
			<i class="icofont-graffiti"></i>
			 Galerie
			<i class="icofont-graffiti"></i>
		</a>
	</p>
</section>

<div class="card centre">
	<!-- exemple de fiche -->
	<?php foreach ($streets as $street): ?>
	<article class="articles">
		<header>
			<h2><?= litenPost('detail',$street['id'], $street['name'] ) ?></h2>
		</header>
		<img rel="prefetch" src="<?= $this->root ?>/img/<?= $street['photo'] ?>" data-src="<?= $this->root ?>/img/<?= $street['photo'] ?>"
		<?php if(!empty($street['name'])) : ?>
		alt="<?= $street['name'] ?>"
		<?php else : ?>
		alt="<?= $street['photo'] ?>"
		<?php endif ?>
		class="reduit" >
		<footer>
			<a href="<?= $this->index ?>detail/<?= $street['id'] ?>" title="street <?= $street['id'] ?>">Plus de détails </a>
		</footer>
	</article>
	<?php endforeach ?>
</div>

