<h1>Votre compte</h1>
<!-- page compte -->

<!-- salutation -->
<div class="centre">
     <strong>
    <?= bienvenu(); ?>
	<?php if (isset($_SESSION['auth'])) : ?>
	<?= $_SESSION['auth']['pseudo'] ?>
	<?php endif ?>

 </strong>

</div>
<section class="card">

	<!-- lien vers different page lier au droit-->
	<nav>
		Gestion
		<?php if ($_SESSION['auth']['droit'] == 9) : ?>
		<a class="button" href="<?= $this->index ?>categorie"  title="categorie">Cathegories</a>
		<a class="button" href="<?= $this->index ?>menbre" title="menbre">Menbre</a>
		<a class="button" href="<?= $this->index ?>message" title="message">Message</a>
		<?php endif ?>
		<a class="button" href="<?= $this->index ?>comment" title="commentaire">Commentaires</a>
		<a class="button" href="<?= $this->index ?>street" title="fiche">Streets</a>
		<a class="button" href="<?= $this->index ?>deconnec" title="deconnection">
			<i class="icofont-ui-close"></i>
			Deconnection
			<i class="icofont-ui-close"></i>
		</a>
	</nav>
</section>