<h1>Connection</h1>
<!-- message erreur suit reponce mot de passe -->
<?php if (!empty($e)): ?>

<div class="alert danger">
	<p>
		erreure de connection:
		<?php if ($e == 2): ?>
		Mais qui es tu ?
		<?php elseif ($e == 3): ?>
		Oui mais ?
		<?php endif ?>
	</p>
</div>
<!-- page connection -->
<?php endif ?>
<form action="?p=setconnection" method="post" class="form">
	<div class="field">
		<label for="pseudo">Entrer votre pseudo ou email: </label>
		<input type="text" name="pseudo" id="pseudo" required>
		<span></span>
	</div>
	<div class="field">
		<label for="password">Entrer votre mot de pass: </label>
		<input type="password" name="password" id="password" required>
		<span></span>
	</div>
	<div class="field">
		<button type="submit" class="button"><i class="icofont-ui-check"></i>Entrer</button>
	</div>
	<?php if (empty($_SESSION['auth'])) : ?>
	<div class="">
		<a href="?p=oublier" title="mot de pass oublier">Mot de pass oublier</a>
		<a href="?p=addCompte" title="Création compte">Création compte</a>
	</div>
	<?php endif ?>
</form>