<!-- page de modification des fiche -->
<h1>Modification street Art</h1>

<?php if (trim($street['statut']) == 'effacée') : ?>
		<article class="card article efface">
		<?php else : ?>
		<article class="card article">
	<?php endif ?>

	<form action="<?= $this->index ?>upposts/<?= $street['id'] ?>" method="post" class="form" enctype='multipart/form-data'>
   <div class="field">
	
		<img <?= redimage('<?= $this->root ?>/img/'.$street['photo'].'',300); ?>
		 rel="prefetch" src="<?= $this->root ?>/img/<?= $street['photo'] ?>"
		<?php if(!empty($street['name'])) : ?>
		alt="<?= $street['name'] ?>"
		<?php else : ?>
		alt="<?= $street['photo'] ?>"
		<?php endif ?>
		class="photo" >
		<?= lienGoogle($street['adresse']) ?>
	</div>
		<div class="field">
			<label for="name">Nom: </label>
			<small>
				Nom de l'oeuvre si vous la connaiser
			</small>
			<input type="text" name="name" id="name"value="<?= $street['name'] ?>">
		</div>
		<div class="field">
			<label for="description">Description: </label>
			<small>
				Descriver le street Art si elle est peinte, ou collée eventuellemnet le non du créateur
			</small>
			<textarea type="text" name="description" id="description"><?= ($street['description']) ?></textarea>
		</div>
		<div class="field">
			<label for="categorie">Catégorie: </label>
			<small>
				Quelle style de street peinte, papier collée,
			</small>
			<select name="categorie" id="categorie">
				<?php foreach ($categories as $categorie) : ?>
				<option value="<?= $categorie['id'] ?>"
					<?php if ($categorie['name'] == $street['categorie']) : ?>
					selected
					<?php endif ?>
					>
					<?= ucfirst($categorie['name']) ?>
					
				</option>
				<?php endforeach ?>
			</select>
		</div>
		<div class="field">
			<label for="dateCreation">Date de création: </label>
			<small>
				date de création de l'oeuvre, si vous connaiser juste l'année mettre 01/01/année de création oulaisser vide
			</small>
			<input type="date" name="dateCreation" id="dateCreation"value="<?= ($street['dateCreation']) ?>">
		</div>
		<div class="field">
			<label for="adresse">Adresse: </label>
			<small>
				Adresse ou se trouve le street Art
			</small>
			<input type="text" name="adresse" id="adresse" placeholder="exemple: 23 rue du streetArt lyon"value="<?= ($street['adresse']) ?>"required>
			<input type="hidden" name="latitude" id="latitude" value="<?= ($street['latitude']) ?>">
			<input type="hidden" name="longitude" id="longitude" value="<?= ($street['longitude']) ?>">
			<div id="adres" class="card">
				<label for="suggestion rue">Suggestion de rue: </label>
				<small>
					cliquez dessus
				</small>
				<div id="address" class="card"></div>
			</div>
		</div>
		<!-- les admins peuvent modifier le nombre de vote -->
		<?php if ($_SESSION['auth']['droit'] == 9) : ?>
		<div class="field">
			<label for="valid">vote: </label>
			si depasse 5 elle sera visible :
			<input type="number" name="valid" id="valid"value="<?= ($street['valid']) ?>">
		</div>
		<select name="user" id="user">
				<?php foreach ($users as $user) : ?>
				<option value="<?= $user['id'] ?>"
					<?php if ($street['pseudo'] == $user['pseudo']) : ?>
					selected
					<?php endif ?>
					>
					<?= ucfirst($user['pseudo']) ?>
					
				</option>
				<?php endforeach ?>
			</select>
		<!-- les admins peuvent modifier le statut -->
		<div class="field">
			<label for="statut">statut: </label>
			<small>
				Quelle style de street peinte, papier collée,
			</small>
			<select name="statut" id="statut">
				<?php foreach ($statuts as $statut) : ?>
				<option value="<?= $statut['id'] ?>"
					<?php if ($statut['statut'] == $street['statut']) : ?>
					selected
					<?php endif ?>
					>
					<?= ($statut['statut']) ?>
				</option>
				<?php endforeach ?>
			</select>
		</div>
		<?php else : ?>
		<!-- ce que voie les non admin -->
		<div class="field">
			<label for="valid">vote: </label>
			si depasse 5 votes, elle sera visible par tous le monde:
			<?= ($street['valid']) ?>
			 votes
			<input type="hidden" name="valid" id="valid" value="<?= ($street['valid']) ?>">
		</div>
		<?php endif ?>
		<!--
		<div class="">
			-->
			<!--
			<label for="photo">photo: </label>
			-->
			<!--
			<input type="file" id="photo" name="photo" accept="image/png, image/jpeg, image/jpg" >
			-->
			<!--
		</div>
		-->
		<div class="">
			<button type="submit" class="botton"><i class="icofont-ui-check"></i>Modifier / Sauvegarder</button>
		</div>
	</form>
</article>
