<h1>Mot de pass oublier</h1>

<form action="./oublier.php" method="post" class="form">
    <div class="field">
        <label for="name">Entrer votre pseudo: </label>
        <input type="text" name="pseudo" id="pseudo" required><span></span>
    </div>
    <div class="field">
        <label for="name">Entrer votre email: </label>
        <input type="text" name="email" id="email" required><span></span>
    </div>
    <div class="field">
        <label for="password">Entrer votre mot de pass: </label>
        <input type="password" name="password" id="password" required><span></span>
    </div>
    <div class="field">
        <button type="submit" class="button"><i class="icofont-ui-check"></i>Entrer</button>
    </div>
    <?php if (empty($_SESSION['auth'])) : ?>
        <div class="">
            
            <a href="?p=addCompte" title="Création compte">Création compte</a>
        </div>
    <?php endif ?>
</form>